#!/usr/bin/env bash
# Depends-on: icoutils inkscape

for size in 36 48 50 57 64 72 80 96 114 128 144 173
do
    inkscape -z --export-background=FFFFFF --export-png=icon-${size}px.png --export-width=${size} --export-height=${size} icon.svg
done

# Default
cp icon-128px.png default.png

# Android
cp icon-36px.png android/ldpi.png
cp icon-48px.png android/mdpi.png
cp icon-72px.png android/hdpi.png
cp icon-96px.png android/xhdpi.png

# Bada
cp icon-128px.png bada/default.png

# Bada WAC
cp icon-48px.png bada-wac/type5.png
cp icon-50px.png bada-wac/type3.png
cp icon-80px.png bada-wac/type4.png

# BlackBerry
cp icon-80px.png blackberry/default.png

# iOS
cp icon-57px.png  ios/iphone.png
cp icon-72px.png  ios/ipad.png
cp icon-114px.png ios/iphone-retina.png
cp icon-144px.png ios/ipad-retina.png

# Tizen
cp icon-128px.png tizen/default.png

# WebOS
cp icon-64px.png  webos/default.png

# Windows Phone
cp icon-48px.png  windows-phone/default.png
cp icon-173px.png windows-phone/tile.png

# Removes useless files
rm -f icon-*px.png
