#!/usr/bin/env ruby
# Depends-on: icoutils inkscape

SOURCE_SIZE = 800

EXPORTS = {
  android: {
    "screen-ldpi-landscape"  => {width: 320,  height: 200},
    "screen-ldpi-portrait"   => {width: 200,  height: 320},
    "screen-mdpi-landscape"  => {width: 480,  height: 320},
    "screen-mdpi-portrait"   => {width: 320,  height: 480},
    "screen-hdpi-landscape"  => {width: 800,  height: 480},
    "screen-hdpi-portrait"   => {width: 480,  height: 800},
    "screen-xhdpi-landscape" => {width: 1280, height: 720},
    "screen-xhdpi-portrait"  => {width: 720,  height: 1280},
  },
  bada: {
    # "screen-landscape"  => {width: 800,  height: 480},
    "screen-portrait"   => {width: 480,  height: 800},
  },
  "bada-wac" => {
    "screen-type3"  => {width: 320,  height: 480},
    "screen-type4"  => {width: 480,  height: 800},
    "screen-type5"  => {width: 240,  height: 400},
  },
  blackberry: {
    "screen-225"  => {width: 225,  height: 225}, # Icon?
  },
  ios: {
    "screen-ipad-landscape-2x"   => {width: 2048,  height: 1536},
    "screen-ipad-landscape"      => {width: 1024,  height: 768},
    "screen-ipad-portrait-2x"    => {width: 1536,  height: 2048},
    "screen-ipad-portrait"       => {width: 768,   height: 1024},
    "screen-iphone-landscape-2x" => {width: 960,   height: 640},
    "screen-iphone-landscape"    => {width: 480,   height: 320},
    "screen-iphone-portrait-2x"  => {width: 640,   height: 960},
    "screen-iphone-portrait"     => {width: 320,   height: 480},
  },
  webos: {
    "screen-64"  => {width: 64,  height: 64}, # Icon?
  },
  "windows-phone" => {
    "screen-portrait" => {width: 480,  height: 800, format: :jpg},
  }
}

for os, exports in EXPORTS
  for name, options in exports
    ratio = SOURCE_SIZE.to_f / [options[:width], options[:height]].max
    width, height = (options[:width] * ratio).round, (options[:height] * ratio).round
    x0, y0 = (SOURCE_SIZE - width)/2, (SOURCE_SIZE - height)/2
    x1, y1 = x0 + width, y0 + height
    puts "#{os}/#{name}: #{options[:width]}x#{options[:height]} from #{x0}:#{y0} -> #{x1}:#{y1} (#{width}x#{height})"
    `inkscape -z --export-background=FFFFFF --export-png=#{os}/#{name}.png --export-width=#{options[:width]} --export-height=#{options[:height]} --export-area=#{x0}:#{y0}:#{x1}:#{y1} screen.svg`
    if options[:format]
      `convert #{os}/#{name}.png #{os}/#{name}.#{options[:format]}`
      `rm #{os}/#{name}.png`
    end
  end
end
